CC=mpicc -std=c99
CFLAGS=-I include/
OBJS=prime
SRC=src/
OBJS= rnd.o ziggurat.o lib.o


all:	bucketSort_MPI

bucketSort_MPI:	$(OBJS) $(SRC)bucketSort_MPI.c
	$(CC) -o bucketSort_MPI $(CFLAGS) $(OBJS) $(SRC)bucketSort_MPI.c -lm
	rm -rf $(OBJS)

rnd.o:	$(SRC)rnd.c
	$(CC) $(CFLAGS) -c $(SRC)rnd.c
	
ziggurat.o: $(SRC)ziggurat.c
	$(CC) $(CFLAGS) -c $(SRC)ziggurat.c

lib.o: $(SRC)lib.c
	$(CC) $(CFLAGS) -c $(SRC)lib.c

clean:
	rm -rf bucketSort_MPI
	rm -rf $(OBJS)
